Lint Python code with ruff
fake-useragent/fake-useragent pull request #172
Opened 2023-03-13 13:59 UTC by cclauss

[Ruff](https://beta.ruff.rs/) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) including bandit, isort, pylint, pyupgrade, and flake8 plus its plugins, and is written in Rust for speed.

The `ruff` Action uses minimal steps to run in ~10 seconds, rapidly providing intuitive GitHub Annotations to contributors.

![image](https://user-images.githubusercontent.com/3709715/223758136-afc386d2-70aa-4eff-953a-2c2d82ceea23.png)

2023-03-13 17:30 UTC, melroy89 commented
OK. But I'm already running black. Black is also an auto formatter / linter.

Will this not interfere with Black?

2023-03-13 17:35 UTC, cclauss commented
https://beta.ruff.rs/docs/faq/#is-ruff-compatible-with-black
TL;DR: Black is a formatter and Ruff is a linter that has been designed to be compatible with Black.

2023-03-20 20:33 UTC, melroy89 requested changes

2023-03-20 20:33 UTC, melroy89 commented on pyproject.toml
> +target-version = "py37"
Since `isort` isn't supported anymore for Python 3.7. Should we move to Python 3.8 here as well maybe?

2023-03-20 20:33 UTC, melroy89 commented on pyproject.toml
> +target-version = "py37"
(also maybe rebase, just to be sure)

2023-03-20 21:18 UTC, cclauss commented on pyproject.toml
> +target-version = "py37"
Rebased.

Py37 still has several months before EOL -- https://devguide.python.org/versions/#versions

2023-03-20 21:20 UTC, melroy89 commented on pyproject.toml
> +target-version = "py37"
hm ok. Since 3.7 was giving issues during GitHub Actions, I removed it from the workflow and tox.

2023-03-20 21:20 UTC, melroy89 approved these changes

2023-03-20 21:20 UTC, merged